[0m10:11:45.971129 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E993D99550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E991F39310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E994E93ED0>]}


============================== 10:11:46.000472 | 5eee9a84-0cc4-4699-8c57-a06ff1f62bf7 ==============================
[0m10:11:46.000472 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:11:46.001588 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\LENOVO 14\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:11:46.044186 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/LENOVO 14/.dbt')}
[0m10:11:46.045114 [info ] [MainThread]: Creating dbt configuration folder at 
[0m10:12:12.715802 [debug] [MainThread]: Starter project path: C:\LILI\Project_DBT\env\Lib\site-packages\dbt\include\starter_project
[0m10:12:12.771814 [info ] [MainThread]: 
Your new dbt project "belajar_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:12:12.776455 [info ] [MainThread]: Setting up your profile.
[0m10:16:13.719762 [info ] [MainThread]: Profile belajar_dbt written to C:\Users\LENOVO 14\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:16:13.722663 [debug] [MainThread]: Command `dbt init` succeeded at 10:16:13.722265 after 267.92 seconds
[0m10:16:13.724223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E995095220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E994F269F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E994D46AD0>]}
[0m10:16:13.728585 [debug] [MainThread]: Flushing usage events
[0m10:16:15.063329 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:25:10.572512 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1948C9550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F192A65310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1959D3ED0>]}


============================== 10:25:10.577103 | 69414ab4-3532-4fdf-8ceb-0c638a3f21b7 ==============================
[0m10:25:10.577103 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:25:10.578011 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\LENOVO 14\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:25:10.607315 [info ] [MainThread]: dbt version: 1.9.3
[0m10:25:10.608115 [info ] [MainThread]: python version: 3.13.2
[0m10:25:10.608993 [info ] [MainThread]: python path: C:\LILI\Project_DBT\env\Scripts\python.exe
[0m10:25:10.609722 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m10:25:10.703397 [info ] [MainThread]: Using profiles dir at C:\Users\LENOVO 14\.dbt
[0m10:25:10.704180 [info ] [MainThread]: Using profiles.yml file at C:\Users\LENOVO 14\.dbt\profiles.yml
[0m10:25:10.704780 [info ] [MainThread]: Using dbt_project.yml file at C:\LILI\Project_DBT\dbt_project.yml
[0m10:25:10.706215 [info ] [MainThread]: adapter type: postgres
[0m10:25:10.706911 [info ] [MainThread]: adapter version: 1.9.0
[0m10:25:10.707556 [info ] [MainThread]: Configuration:
[0m10:25:10.708167 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m10:25:10.708730 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m10:25:10.709478 [info ] [MainThread]: Required dependencies:
[0m10:25:10.710119 [debug] [MainThread]: Executing "git --help"
[0m10:25:10.719065 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m10:25:10.720190 [info ] [MainThread]: Connection:
[0m10:25:10.720919 [info ] [MainThread]:   host: localhost
[0m10:25:10.721526 [info ] [MainThread]:   port: 5433
[0m10:25:10.722080 [info ] [MainThread]:   user: postgres
[0m10:25:10.722669 [info ] [MainThread]:   database: penjualan
[0m10:25:10.723237 [info ] [MainThread]:   schema: global
[0m10:25:10.723802 [info ] [MainThread]:   connect_timeout: 10
[0m10:25:10.724398 [info ] [MainThread]:   role: None
[0m10:25:10.724955 [info ] [MainThread]:   search_path: None
[0m10:25:10.725753 [info ] [MainThread]:   keepalives_idle: 0
[0m10:25:10.727474 [info ] [MainThread]:   sslmode: None
[0m10:25:10.728138 [info ] [MainThread]:   sslcert: None
[0m10:25:10.728705 [info ] [MainThread]:   sslkey: None
[0m10:25:10.729305 [info ] [MainThread]:   sslrootcert: None
[0m10:25:10.729894 [info ] [MainThread]:   application_name: dbt
[0m10:25:10.730473 [info ] [MainThread]:   retries: 1
[0m10:25:10.731532 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m10:25:10.931909 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m10:25:14.114420 [debug] [MainThread]: Using postgres connection "debug"
[0m10:25:14.115019 [debug] [MainThread]: On debug: select 1 as id
[0m10:25:14.115720 [debug] [MainThread]: Opening a new connection, currently in state init
[0m10:25:14.179708 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5433 failed: FATAL:  password authentication failed for user "postgres"

[0m10:25:14.236032 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m10:25:14.236951 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m10:25:14.237650 [debug] [MainThread]: On debug: No close available on handle
[0m10:25:14.238376 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m10:25:14.239568 [info ] [MainThread]: [31m3 checks failed:[0m
[0m10:25:14.240654 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\LILI\Project_DBT\dbt_project.yml> not found

[0m10:25:14.241555 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m10:25:14.242412 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5433 failed: FATAL:  password authentication failed for user "postgres"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m10:25:14.244249 [debug] [MainThread]: Command `dbt debug` failed at 10:25:14.244005 after 3.87 seconds
[0m10:25:14.244857 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m10:25:14.245240 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F195BC3100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F195BE6690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F195A7E140>]}
[0m10:25:14.245687 [debug] [MainThread]: Flushing usage events
[0m10:25:15.335786 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:01:04.236793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E431E9550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E41385310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E442E7ED0>]}


============================== 11:01:04.250353 | 346e8b76-8375-4314-b5e9-a6a659df8518 ==============================
[0m11:01:04.250353 [info ] [MainThread]: Running with dbt=1.9.3
[0m11:01:04.253552 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\LENOVO 14\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:01:04.322094 [info ] [MainThread]: dbt version: 1.9.3
[0m11:01:04.323907 [info ] [MainThread]: python version: 3.13.2
[0m11:01:04.325683 [info ] [MainThread]: python path: C:\LILI\Project_DBT\env\Scripts\python.exe
[0m11:01:04.334439 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m11:01:04.862922 [info ] [MainThread]: Using profiles dir at C:\Users\LENOVO 14\.dbt
[0m11:01:04.864346 [info ] [MainThread]: Using profiles.yml file at C:\Users\LENOVO 14\.dbt\profiles.yml
[0m11:01:04.865632 [info ] [MainThread]: Using dbt_project.yml file at C:\LILI\Project_DBT\dbt_project.yml
[0m11:01:04.868257 [info ] [MainThread]: adapter type: postgres
[0m11:01:04.869615 [info ] [MainThread]: adapter version: 1.9.0
[0m11:01:04.872182 [info ] [MainThread]: Configuration:
[0m11:01:04.873736 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:01:04.875009 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:01:04.876449 [info ] [MainThread]: Required dependencies:
[0m11:01:04.877932 [debug] [MainThread]: Executing "git --help"
[0m11:01:04.954853 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:01:04.956301 [debug] [MainThread]: STDERR: "b''"
[0m11:01:04.957267 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:01:04.958700 [info ] [MainThread]: Connection:
[0m11:01:04.960131 [info ] [MainThread]:   host: localhost
[0m11:01:04.961423 [info ] [MainThread]:   port: 5433
[0m11:01:04.962844 [info ] [MainThread]:   user: postgres
[0m11:01:04.964225 [info ] [MainThread]:   database: penjualan
[0m11:01:04.965583 [info ] [MainThread]:   schema: global
[0m11:01:04.967211 [info ] [MainThread]:   connect_timeout: 10
[0m11:01:04.969063 [info ] [MainThread]:   role: None
[0m11:01:04.970953 [info ] [MainThread]:   search_path: None
[0m11:01:04.972180 [info ] [MainThread]:   keepalives_idle: 0
[0m11:01:04.973517 [info ] [MainThread]:   sslmode: None
[0m11:01:04.974844 [info ] [MainThread]:   sslcert: None
[0m11:01:04.976350 [info ] [MainThread]:   sslkey: None
[0m11:01:04.977830 [info ] [MainThread]:   sslrootcert: None
[0m11:01:04.979245 [info ] [MainThread]:   application_name: dbt
[0m11:01:04.980926 [info ] [MainThread]:   retries: 1
[0m11:01:04.983171 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m11:01:05.689169 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m11:01:12.934053 [debug] [MainThread]: Using postgres connection "debug"
[0m11:01:12.936568 [debug] [MainThread]: On debug: select 1 as id
[0m11:01:12.937822 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:01:13.274277 [debug] [MainThread]: SQL status: SELECT 1 in 0.336 seconds
[0m11:01:13.277180 [debug] [MainThread]: On debug: Close
[0m11:01:13.278486 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m11:01:13.303018 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:01:13.305115 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\LILI\Project_DBT\dbt_project.yml> not found

[0m11:01:13.308009 [debug] [MainThread]: Command `dbt debug` failed at 11:01:13.307609 after 9.39 seconds
[0m11:01:13.309004 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m11:01:13.310103 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E444D3100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E444F6E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019E4438F460>]}
[0m11:01:13.311621 [debug] [MainThread]: Flushing usage events
[0m11:01:14.520211 [debug] [MainThread]: An error was encountered while trying to flush usage events
